#!/usr/bin/env bash
# This script adds contents of cwd, commits with custom input (no spaces) and pushes to GitHub

if [ -z "$1" ]
then
	echo "Last commit message from working branch:"
	git log -1 | tail -n 1 | tr -d ' '
	read -p "ENTER COMMIT: " COMMIT
	git add .
	git commit -m "$COMMIT"
	git push
	echo "COMMIT NAME: $COMMIT"
	echo COMPLETED
else
	git add .
	git commit -m "$1"
	git push
	echo "COMMIT NAME: $COMMIT"
	echo ---- COMPLETED ----
fi
