#!/bin/bash
# template for C file

case $1 in
	*)
	touch $1
	echo "#include \".h\"" >> $1
	echo "/**" >> $1
	echo "* " >> $1
	echo "*/" >> $1
	echo "" >> $1
	echo "{" >> $1
	echo "	" >> $1
	echo "}" >> $1
esac
